### PR TITLE
Add `UnorderedSet` pagination example

### PR DESCRIPTION
**Pull request by evgenykuzyakov**

### CODE REVIEW

**Review by austinabell — COMMENTED** [review]
This isn't needed to be written like this with the `near_sdk::store` collections. We should probably note somewhere in this section that this is only for `near_sdk::collections`. Since the new version has an optimized nth implementation, can just write it as `.iter().skip(from_index).take(limit)`

**Review by mikedotexe — APPROVED** [review]
I think this would be very useful to have in the docs, thanks, Eugene

**Comment by austinabell** [comment]
Note: After https://github.com/near/near-sdk-rs/pull/634 this will no longer be required in 4.0, maybe I can create an issue to update this to indicate this is just a workaround for old version?

**Comment by austinabell** [comment]
Closing this, the optimization is added for both types of collections in 4.0, so not worth adding these docs

**Pull request closed without merging**
