### PR TITLE
Updates to some links on reducing-contract-size

### PR DESCRIPTION
**Pull request by Buckram123**
One link updated and can't find anywhere 'Tiny contract'

### CODE REVIEW

**Comment by mikedotexe** [comment]
Hello my friend, and thank you for contributing!

I was unable to reproduce the problem, however. Here's an animated GIF of my clicking through the link that you're altering:

near-sdk-link-resolving

**Comment by Buckram123** [comment]
Oops.. forgot check hyperlinks on website, not on the github. 404 link on 'Tiny contract' is still actual tho

**Review by austinabell — APPROVED** [review]
@mikedotexe decision to update/remove, but I think it makes sense to not link to nearcore master. If it was important, maybe we pin the commit?

**Comment by mikedotexe** [comment]
Hey @Buckram123 thanks for noticing that the link wasn't resolving. I think the tiny contract example may still be helpful for other individuals, so I've pinned it to a commit where it exists. Please see #90 as I wasn't able to "add suggestion" on this PR since it was a deletion.

Thanks again!

**Pull request closed without merging**
